### ISSUE TITLE
can't install inkscape-quartz on mountain lion

### ISSUE THREAD

**Issue by borismarin** [acornejo/homebrew-quartz#1]
I get the following error message  
   brew tap acornejo/quartz
   brew install inkscape-quartz
  [...]
  Error: inkscape-quartz dependency acornejo/quartz/cairo-quartz not installed with:
  --alt

best,
boris

**Comment by acornejo** [comment]
Hi Boris,

I stoppped maintaining this formula a while ago, since I found there was a dmg available here:

http://inkscape.13.x6.nabble.com/Mac-OS-X-0-48-4-RC5-td4966075.html

I encourage you to give it a try, I've been using it without major problems for a while.

Nevertheless, if you are still interested in building it from source, let me know and I can look at the formula again (I thought no one else was using it).

**Comment by borismarin** [comment]
Alex,

thanks for the link. I'll give it a try.

**Comment by acornejo** [comment]
I'm closing this issue, I believe I fixed the problem with the latest commit.
