### ISSUE TITLE
Works on Maverick?

### ISSUE THREAD

**Issue by corysimmons** [acornejo/homebrew-quartz#3]
ooc before i do the big build, wasn't in readme

**Comment by acornejo** [comment]
Hi Cory,

Haven't tested it in mavericks, I am upgrading right now to see if it works.

You might have noticed that I have stopped actively maintaining this homebrew repository for quite some time, mostly because I stopped using it myself and I figured no one else was using it. Personally I've been using a binary distribution of inkscape for OSX which has worked well so far (and helps me avoid compiling everything from scratch). I've always hoped the inkscape people incorporate the patches into a working OSX release, but unfortunately there seems little interested on this on part of the maintainers.

In any case, if you are interested in trying a binary solution, head over here: http://inkscape.13.x6.nabble.com/Mac-OS-X-0-48-4-RC5-td4966075.html

On the other hand, if you are interested in getting inkscape working with brew from source, let me know and I'll look into it (I might be interested too, only to get the console version of inkscape working properly). To get this homebrew repository back up to date I'll need at least one tester.

Cheers,

Alex

**Comment by corysimmons** [comment]
What about just using `brew install https://raw.github.com/btel/homebrew/inkscape_clang/Library/Formula/inkscape.rb --HEAD`? I think @btel might have a PR in for this.

I'm not sure if you need to have X11 or not, but it seems to work.

**Comment by acornejo** [comment]
Short answer, it does need X11.

The point of having a "quartz" release is not to require x11 and to use the native quartz backend (instead of xquartz, aka x11)

Using a pure quartz backend has the nice side effect of running faster and using less memory than when running through an x11 layer.

If you are ok with  using x11 I would advocate you use that formula instead of this one, or just switch to the official inkscape distribution for osx, available here:

http://www.inkscape.org/en/download/mac-os/

(again, this will use xquartz and not quartz, which is the point of this repository).

**Comment by corysimmons** [comment]
Ok, I don't know the differences between XQuartz and Quartz but how much faster does Quartz run?

**Comment by acornejo** [comment]
I'm sorry, I have not run benchmarks so I can't give you any numbers (running fair benchmarks would be challenging, since we are talking about the UI here, not the internal svg c++ engine of inkscape).

Briefly, quartz is the graphics layer responsible for drawing stuff in OS X (see here http://en.wikipedia.org/wiki/Quartz_(graphics_layer))

Inkscape was developed using GTK, which traditionally is run in linux on top of the "X window system". XQuartz or X11 is simply a port of the entire X window system api to OS X (the naming is confusing here, because there used to be a project called X11.app which Apple stopped supporting, XQuartz is essentially the opensource version of X11.app).

Thus, when running inkscape through Xquartz/X11 what happens you add another layer of indirection. Inkscape renders through GTK, GTK renders through XQuartz/X11, and XQuartz finally renders through Quartz.

When running inkscape through quartz, the pipeline is simpler, namely inkscape->gtk->quartz (as opposed to inkscape->gtk->x11->quartz). I hope that helps.

**Comment by corysimmons** [comment]
Ah, I see. Benchmarks would be interesting to really get behind this project. =)
